export const NON_PROGRESS_SIGNALS = [
  'authRedirect',
  'not interactive',
  'is stale',
  'timed out',
  'No significant visual change',
  'element not found',
  'no longer available',
  'Login page detected',
  'CAPTCHA',
  '404',
  'Access Denied',
  'Forbidden',
  'net::ERR_',
  'Navigation timeout',
  'Protocol error',
  'bot-check',
  'captcha detected',
  'Blocking page detected',
  'blocked by',
  'network security',
  'been blocked',
] as const;
