import type { SchemaProperty } from './schema-validator';
export interface StrategyResult { data: Record<string, unknown>; source: string; fieldsFound: string[]; }

export function buildJsonLdExtractor(fieldNames: string[]): string {
  return `(function(fn){var r={};var sc=document.querySelectorAll('script[type="application/ld+json"]');for(var i=0;i<sc.length;i++){try{var d=JSON.parse(sc[i].textContent||'');var it=Array.isArray(d)?d:(d['@graph']?d['@graph']:[d]);for(var j=0;j<it.length;j++){var item=it[j];if(!item||typeof item!=='object')continue;for(var k=0;k<fn.length;k++){var f=fn[k];if(r[f]!=null)continue;if(item[f]!==undefined){r[f]=item[f];continue}var mp={'name':['name','headline'],'title':['name','headline'],'price':['price','lowPrice'],'currency':['priceCurrency'],'description':['description'],'image':['image','thumbnailUrl'],'image_url':['image','thumbnailUrl'],'rating':['ratingValue','aggregateRating'],'review_count':['reviewCount','ratingCount'],'author':['author'],'published_date':['datePublished','dateCreated'],'date':['datePublished','dateCreated','dateModified'],'url':['url'],'brand':['brand'],'sku':['sku'],'category':['category'],'availability':['availability']};var fm=mp[f.toLowerCase()]||[];for(var m=0;m<fm.length;m++){if(item[fm[m]]!==undefined){var v=item[fm[m]];if(typeof v==='object'&&v&&!Array.isArray(v)){v=v.name||v['@value']||v.value||JSON.stringify(v)}if(fm[m]==='aggregateRating'&&typeof v==='object'){v=v.ratingValue}r[f]=v;break}}if(r[f]===undefined&&item.offers){var of=Array.isArray(item.offers)?item.offers:[item.offers];for(var o=0;o<of.length;o++){for(var x=0;x<fm.length;x++){if(of[o][fm[x]]!==undefined){r[f]=of[o][fm[x]];break}}if(r[f]!==undefined)break}}}}}catch(e){}}return r})(${JSON.stringify(fieldNames)})`;
}

export function buildMicrodataExtractor(fieldNames: string[]): string {
  return `(function(fn){var r={};for(var i=0;i<fn.length;i++){var f=fn[i];if(r[f]!=null)continue;var pn=[f,f.replace(/_/g,''),f.toLowerCase()];for(var p=0;p<pn.length;p++){var el=document.querySelector('[itemprop="'+pn[p]+'"]');if(el){var v=el.getAttribute('content')||el.textContent?.trim()||'';if(v){r[f]=v;break}}}}return r})(${JSON.stringify(fieldNames)})`;
}

export function buildOpenGraphExtractor(fieldNames: string[]): string {
  return `(function(fn){var r={};var mp={'title':['og:title','twitter:title'],'name':['og:title','twitter:title','og:site_name'],'description':['og:description','twitter:description','description'],'image':['og:image','twitter:image'],'image_url':['og:image','twitter:image'],'url':['og:url'],'author':['author','article:author'],'published_date':['article:published_time','date'],'date':['article:published_time','date'],'site_name':['og:site_name']};for(var i=0;i<fn.length;i++){var f=fn[i];if(r[f]!=null)continue;var cd=mp[f.toLowerCase()]||[f];for(var c=0;c<cd.length;c++){var m=document.querySelector('meta[property="'+cd[c]+'"]')||document.querySelector('meta[name="'+cd[c]+'"]');if(m){var ct=m.getAttribute('content');if(ct){r[f]=ct;break}}}if(!r[f]&&(f==='url'||f==='canonical')){var lk=document.querySelector('link[rel="canonical"]');if(lk)r[f]=lk.getAttribute('href')}}return r})(${JSON.stringify(fieldNames)})`;
}

export function buildCssHeuristicExtractor(fieldNames: string[], schemaProps: Record<string, SchemaProperty>, scopeSelector?: string): string {
  return `(function(fn,sp,scope){var r={};var root=scope?document.querySelector(scope):document.body;if(!root)root=document.body;function gt(el){if(!el)return null;if(el.tagName==='IMG')return el.src||el.getAttribute('data-src')||null;return(el.textContent?.trim()||'').slice(0,500)||null}function q1(ss){for(var i=0;i<ss.length;i++){try{var el=root.querySelector(ss[i]);if(el)return el}catch(e){}}return null}for(var i=0;i<fn.length;i++){var f=fn[i];if(r[f]!=null)continue;var fl=f.toLowerCase(),fk=f.replace(/([A-Z])/g,'-$1').toLowerCase().replace(/^-/,'');var ss=['[class*="'+fl+'"]','[class*="'+fk+'"]','[data-'+fk+']','[data-testid*="'+fl+'"]','[aria-label*="'+fl+'"]','#'+fl,'#'+fk];var isI=fl.includes('image')||fl.includes('img')||fl.includes('photo')||fl.includes('thumbnail');if(isI)ss.unshift('img[class*="'+fl+'"]','[class*="'+fl+'"] img','img[class*="product"]','meta[property="og:image"]');if(fl.includes('price')||fl.includes('cost'))ss.unshift('[class*="price"]','[data-price]','[itemprop="price"]','.price');if(fl.includes('rating')||fl.includes('score'))ss.unshift('[class*="rating"]','[class*="stars"]','[itemprop="ratingValue"]','[aria-label*="rating"]');var el=q1(ss);if(el){if(isI)r[f]=el.src||el.getAttribute('data-src')||el.getAttribute('content')||gt(el);else if(el.hasAttribute('content'))r[f]=el.getAttribute('content');else if(el.hasAttribute('data-'+fk))r[f]=el.getAttribute('data-'+fk);else r[f]=gt(el)}}return r})(${JSON.stringify(fieldNames)},${JSON.stringify(schemaProps)},${JSON.stringify(scopeSelector||null)})`;
}

export function buildMultipleItemExtractor(fieldNames: string[], schemaProps: Record<string, SchemaProperty>, scopeSelector?: string): string {
  return `(function(fn,sp,scope){var root=scope?document.querySelector(scope):document.body;if(!root)root=document.body;function gt(el){if(!el)return null;if(el.tagName==='IMG')return el.src||el.getAttribute('data-src')||null;return(el.textContent?.trim()||'').slice(0,500)||null}var cs=['[role="list"]','[class*="list"]','[class*="grid"]','[class*="results"]','[class*="items"]','[class*="products"]','[class*="cards"]','table tbody','ul','ol'];var items=[];for(var c=0;c<cs.length;c++){try{var cd=root.querySelector(cs[c]);if(!cd)continue;var ch=cd.children;if(ch.length<2)continue;var ft=ch[0].tagName,sc=0;for(var x=0;x<ch.length;x++)if(ch[x].tagName===ft)sc++;if(sc/ch.length>0.7){for(var y=0;y<Math.min(ch.length,50);y++)items.push(ch[y]);break}}catch(e){}}if(!items.length){var rows=root.querySelectorAll('tr');if(rows.length>1)for(var r=1;r<Math.min(rows.length,51);r++)items.push(rows[r])}if(!items.length)return[];var res=[];for(var i=0;i<items.length;i++){var it=items[i],ext={},has=false;for(var f2=0;f2<fn.length;f2++){var f=fn[f2],fl=f.toLowerCase(),fk=f.replace(/([A-Z])/g,'-$1').toLowerCase().replace(/^-/,'');var isI=fl.includes('image')||fl.includes('img')||fl.includes('photo');var isL=fl.includes('url')||fl.includes('link')||fl.includes('href');var v=null;if(isI){var img=it.querySelector('img');if(img)v=img.src||img.getAttribute('data-src')}else if(isL){var a=it.querySelector('a[href]');if(a)v=a.href}else{var ss=['[class*="'+fl+'"]','[class*="'+fk+'"]','[itemprop="'+fl+'"]','[data-testid*="'+fl+'"]'];for(var s=0;s<ss.length;s++){try{var el=it.querySelector(ss[s]);if(el){v=gt(el);break}}catch(e){}}}if(!v){if(fl==='title'||fl==='name'||fl==='headline'){var h=it.querySelector('h1,h2,h3,h4,a');if(h)v=(h.textContent?.trim()||'').slice(0,200)}else if(fl.includes('price')){var pe=it.querySelector('[class*="price"],[data-price]');if(pe)v=gt(pe)}else if(fl.includes('description')||fl.includes('snippet')){var de=it.querySelector('p,[class*="desc"],[class*="snippet"]');if(de)v=gt(de)}}ext[f]=v;if(v!==null)has=true}if(has)res.push(ext)}return res})(${JSON.stringify(fieldNames)},${JSON.stringify(schemaProps)},${JSON.stringify(scopeSelector||null)})`;
}
