/**
 * Playwright TypeScript snippet generator (issue #836).
 *
 * Mirrors `formatters/puppeteer.ts` for the same nine tools, emitting
 * Playwright-flavoured calls. Snippets share a `page` variable provided
 * by the file header, which connects over CDP to the same Chrome
 * instance the agent drove.
 */

import { jsLiteral } from './shared';

export const PLAYWRIGHT_SUPPORTED_TOOLS: ReadonlySet<string> = new Set([
  'navigate',
  'interact',
  'form_input',
  'fill_form',
  'page_screenshot',
  'wait_for',
  'javascript_tool',
  'tabs_create',
  'tabs_close',
]);

export const PLAYWRIGHT_FILE_HEADER = [
  '// Generated by openchrome --codegen playwright',
  '// Replay this script with: npx tsx <thisfile>',
  "import { chromium } from 'playwright';",
  '',
  'async function main(): Promise<void> {',
  '  const browser = await chromium.connectOverCDP(process.env.CHROME_URL ?? "http://localhost:9222");',
  '  const context = browser.contexts()[0] ?? (await browser.newContext());',
  '  const pages = context.pages();',
  '  const page = pages[0] ?? (await context.newPage());',
  '',
].join('\n');

export const PLAYWRIGHT_FILE_FOOTER = [
  '',
  '  await browser.close();',
  '}',
  '',
  'main().catch((err) => {',
  '  console.error(err);',
  '  process.exit(1);',
  '});',
  '',
].join('\n');

export function formatPlaywright(
  tool: string,
  args: Record<string, unknown>,
): string | null {
  if (!PLAYWRIGHT_SUPPORTED_TOOLS.has(tool)) return null;
  switch (tool) {
    case 'navigate':
      return formatNavigate(args);
    case 'interact':
      return formatInteract(args);
    case 'form_input':
      return formatFormInput(args);
    case 'fill_form':
      return formatFillForm(args);
    case 'page_screenshot':
      return formatScreenshot(args);
    case 'wait_for':
      return formatWaitFor(args);
    case 'javascript_tool':
      return formatJavascript(args);
    case 'tabs_create':
      return formatTabsCreate(args);
    case 'tabs_close':
      return formatTabsClose(args);
    default:
      return null;
  }
}

function formatNavigate(args: Record<string, unknown>): string {
  const url = args.url as string | undefined;
  if (url === 'back') return '  await page.goBack({ waitUntil: "domcontentloaded" });';
  if (url === 'forward') return '  await page.goForward({ waitUntil: "domcontentloaded" });';
  return `  await page.goto(${jsLiteral(url)}, { waitUntil: "domcontentloaded" });`;
}

function formatInteract(args: Record<string, unknown>): string {
  const action = (args.action as string | undefined) ?? 'click';
  const selector = args.selector as string | undefined;
  const text = args.text as string | undefined;

  if (action === 'click') {
    return `  await page.click(${jsLiteral(selector)});`;
  }
  if (action === 'type' || action === 'fill') {
    return `  await page.fill(${jsLiteral(selector)}, ${jsLiteral(text ?? '')});`;
  }
  if (action === 'hover') {
    return `  await page.hover(${jsLiteral(selector)});`;
  }
  if (action === 'focus') {
    return `  await page.focus(${jsLiteral(selector)});`;
  }
  return [
    `  // interact action="${action}" — replayed as click for fallback compatibility`,
    `  await page.click(${jsLiteral(selector)});`,
  ].join('\n');
}

function formatFormInput(args: Record<string, unknown>): string {
  const selector = args.selector as string | undefined;
  const value = args.value as string | undefined;
  return `  await page.fill(${jsLiteral(selector)}, ${jsLiteral(value ?? '')});`;
}

function formatFillForm(args: Record<string, unknown>): string {
  const fields = (args.fields ?? args.values) as
    | Array<{ selector?: string; value?: string }>
    | Record<string, string>
    | undefined;
  if (!fields) return '  // fill_form: no fields supplied';
  if (Array.isArray(fields)) {
    return fields
      .map((f) => `  await page.fill(${jsLiteral(f.selector)}, ${jsLiteral(f.value ?? '')});`)
      .join('\n');
  }
  return Object.entries(fields)
    .map(([sel, val]) => `  await page.fill(${jsLiteral(sel)}, ${jsLiteral(String(val))});`)
    .join('\n');
}

function formatScreenshot(args: Record<string, unknown>): string {
  const filePath = args.path as string | undefined;
  const fullPage = (args.fullPage as boolean | undefined) ?? false;
  const opts: string[] = [`fullPage: ${fullPage}`];
  if (filePath) opts.push(`path: ${jsLiteral(filePath)}`);
  return `  await page.screenshot({ ${opts.join(', ')} });`;
}

function formatWaitFor(args: Record<string, unknown>): string {
  const type = args.type as string | undefined;
  const value = args.value as string | undefined;
  const timeout = (args.timeout as number | undefined) ?? 30000;
  switch (type) {
    case 'selector':
      return `  await page.waitForSelector(${jsLiteral(value)}, { timeout: ${timeout} });`;
    case 'selector_hidden':
      return `  await page.waitForSelector(${jsLiteral(value)}, { timeout: ${timeout}, state: "hidden" });`;
    case 'function':
      return `  await page.waitForFunction(${jsLiteral(value ?? 'true')}, undefined, { timeout: ${timeout} });`;
    case 'navigation':
      return `  await page.waitForNavigation({ timeout: ${timeout}, waitUntil: "domcontentloaded" });`;
    case 'url_match':
      return `  await page.waitForURL(new RegExp(${jsLiteral(value ?? '.*')}), { timeout: ${timeout} });`;
    case 'timeout':
      return `  await page.waitForTimeout(${Number(value) || 1000});`;
    default:
      return `  // wait_for type="${type ?? 'unknown'}" — no Playwright mapping`;
  }
}

function formatJavascript(args: Record<string, unknown>): string {
  const code = args.code as string | undefined;
  return `  await page.evaluate(${jsLiteral(code ?? '')});`;
}

function formatTabsCreate(args: Record<string, unknown>): string {
  const url = args.url as string | undefined;
  return [
    `  {`,
    `    const newPage = await context.newPage();`,
    `    await newPage.goto(${jsLiteral(url)}, { waitUntil: "domcontentloaded" });`,
    `  }`,
  ].join('\n');
}

function formatTabsClose(args: Record<string, unknown>): string {
  const tabIds = args.tabIds as string[] | undefined;
  const tabId = args.tabId as string | undefined;
  const ids = tabIds && tabIds.length > 0 ? tabIds : tabId ? [tabId] : [];
  if (ids.length === 0) {
    return '  // tabs_close: no tabIds supplied (worker-scoped close not representable as plain playwright)';
  }
  return [
    `  {`,
    `    const targetIds = new Set<string>(${JSON.stringify(ids)});`,
    `    for (const p of context.pages()) {`,
    `      const session = await context.newCDPSession(p);`,
    `      const info = await session.send('Target.getTargetInfo');`,
    `      await session.detach();`,
    `      if (targetIds.has(info.targetInfo.targetId)) await p.close();`,
    `    }`,
    `  }`,
  ].join('\n');
}
