/**
 * Puppeteer TypeScript snippet generator (issue #836).
 *
 * Emits one snippet line (or a small block) per tool call for the nine
 * tools enumerated in the issue: navigate, interact, form_input, fill_form,
 * page_screenshot, wait_for, javascript_tool, tabs_create, tabs_close.
 *
 * Snippets are intentionally minimal — the goal is "what happened",
 * not "production-grade test". They assume a single shared `page`
 * variable (provided by the file header from aggregator.ts) and consume
 * the same `args` object that arrives at the tool handler. Secrets
 * placeholders (`${SECRET:NAME}`) pass through unchanged when the
 * secrets-hook supplies pre-substitution args; otherwise the post-
 * substitution literal value is embedded (see issue #834 dependency).
 */

import { jsLiteral } from './shared';

/**
 * Tools that have a per-tool Puppeteer snippet. The aggregator gates on
 * this set: tools outside it emit only mcp-replay envelopes.
 */
export const PUPPETEER_SUPPORTED_TOOLS: ReadonlySet<string> = new Set([
  'navigate',
  'interact',
  'form_input',
  'fill_form',
  'page_screenshot',
  'wait_for',
  'javascript_tool',
  'tabs_create',
  'tabs_close',
]);

/** Header prepended to the puppeteer TS session file on first append. */
export const PUPPETEER_FILE_HEADER = [
  '// Generated by openchrome --codegen puppeteer',
  '// Replay this script with: npx tsx <thisfile>',
  "import puppeteer from 'puppeteer-core';",
  '',
  'async function main(): Promise<void> {',
  '  const browser = await puppeteer.connect({ browserURL: process.env.CHROME_URL ?? "http://localhost:9222" });',
  '  const pages = await browser.pages();',
  '  let page = pages[0] ?? (await browser.newPage());',
  '',
].join('\n');

/** Footer appended to the puppeteer TS session file at session end. */
export const PUPPETEER_FILE_FOOTER = [
  '',
  '  await browser.disconnect();',
  '}',
  '',
  'main().catch((err) => {',
  '  console.error(err);',
  '  process.exit(1);',
  '});',
  '',
].join('\n');

/**
 * Build a Puppeteer snippet for the given tool call.
 *
 * Returns a string of one or more indented TS statements (no trailing
 * newline; the aggregator adds it). Returns `null` when the tool is not
 * one of the nine supported tools — callers that hit `null` fall back
 * to mcp-replay capture.
 *
 * When `args.tabId` is present the emitted snippet re-selects the correct
 * page from the browser's page list before executing the action, so that
 * multi-tab replays land on the right tab instead of always using the
 * default active page.
 */
export function formatPuppeteer(
  tool: string,
  args: Record<string, unknown>,
): string | null {
  if (!PUPPETEER_SUPPORTED_TOOLS.has(tool)) return null;

  const tabId = args.tabId as string | undefined;
  // Emit a page re-selection block when a tabId is present so that
  // multi-tab replays connect to the correct page rather than defaulting
  // to the first/active page.
  const pageSelectPrefix = tabId
    ? [
        `  {`,
        `    const _allPages = await browser.pages();`,
        `    for (const _p of _allPages) {`,
        `      const _c = await _p.target().createCDPSession();`,
        `      const { targetInfo } = await _c.send('Target.getTargetInfo');`,
        `      await _c.detach();`,
        `      if (targetInfo.targetId === ${jsLiteral(tabId)}) { page = _p; break; }`,
        `    }`,
        `  }`,
      ].join('\n') + '\n'
    : '';

  let snippet: string | null;
  switch (tool) {
    case 'navigate':
      snippet = formatNavigate(args);
      break;
    case 'interact':
      snippet = formatInteract(args);
      break;
    case 'form_input':
      snippet = formatFormInput(args);
      break;
    case 'fill_form':
      snippet = formatFillForm(args);
      break;
    case 'page_screenshot':
      snippet = formatScreenshot(args);
      break;
    case 'wait_for':
      snippet = formatWaitFor(args);
      break;
    case 'javascript_tool':
      snippet = formatJavascript(args);
      break;
    case 'tabs_create':
      snippet = formatTabsCreate(args);
      break;
    case 'tabs_close':
      snippet = formatTabsClose(args);
      break;
    default:
      // Unreachable given the gate above, but the compiler insists.
      return null;
  }

  return pageSelectPrefix ? pageSelectPrefix + snippet : snippet;
}

function formatNavigate(args: Record<string, unknown>): string {
  const url = args.url as string | undefined;
  if (url === 'back') return '  await page.goBack({ waitUntil: "domcontentloaded" });';
  if (url === 'forward') return '  await page.goForward({ waitUntil: "domcontentloaded" });';
  return `  await page.goto(${jsLiteral(url)}, { waitUntil: "domcontentloaded" });`;
}

function formatInteract(args: Record<string, unknown>): string {
  const action = (args.action as string | undefined) ?? 'click';
  const query = (args.query ?? args.text ?? args.selector) as string | undefined;
  const clickCount = action === 'double_click' ? 2 : 1;

  if (!query) return '  // interact: no query supplied; original call captured in mcp-replay JSONL';
  const textSelector = `::-p-text(${query})`;
  if (action === 'hover') {
    return `  await page.hover(${jsLiteral(textSelector)});`;
  }
  if (action === 'click' || action === 'double_click') {
    return `  await page.click(${jsLiteral(textSelector)}, { clickCount: ${clickCount} });`;
  }
  return [
    `  // interact action=${jsLiteral(action)} is not directly mapped; replaying as text click`,
    `  await page.click(${jsLiteral(textSelector)});`,
  ].join('\n');
}

function formatFormInput(args: Record<string, unknown>): string {
  const ref = args.ref as string | undefined;
  const value = args.value as string | undefined;
  const numericBackendId = ref && /^\d+$/.test(ref) ? Number(ref) : null;
  if (numericBackendId !== null) {
    return [
      `  {`,
      `    const client = await page.target().createCDPSession();`,
      `    const { object } = await client.send('DOM.resolveNode', { backendNodeId: ${numericBackendId} });`,
      `    await client.send('Runtime.callFunctionOn', { objectId: object.objectId, functionDeclaration: 'function(){ this.focus(); }' });`,
      `    await page.keyboard.type(${jsLiteral(value ?? '')});`,
      `    await client.detach();`,
      `  }`,
    ].join('\n');
  }
  return [
    `  // form_input used snapshot ref ${jsLiteral(ref)}; ref_N is session-local and not replayable as a CSS selector.`,
    `  // Ensure the intended field is focused before this generated fallback.`,
    `  await page.keyboard.type(${jsLiteral(value ?? '')});`,
  ].join('\n');
}
function formatFillForm(args: Record<string, unknown>): string {
  const fields = (args.fields ?? args.values) as
    | Array<{ selector?: string; value?: string }>
    | Record<string, string>
    | undefined;
  if (!fields) {
    return '  // fill_form: no fields supplied';
  }
  if (Array.isArray(fields)) {
    return fields
      .map((f) =>
        [
          `  await page.click(${jsLiteral(f.selector)}, { clickCount: 3 });`,
          `  await page.type(${jsLiteral(f.selector)}, ${jsLiteral(f.value ?? '')});`,
        ].join('\n'),
      )
      .join('\n');
  }
  // Map form { "#sel": "value", ... }
  return Object.entries(fields)
    .map(([sel, val]) =>
      [
        `  await page.click(${jsLiteral(sel)}, { clickCount: 3 });`,
        `  await page.type(${jsLiteral(sel)}, ${jsLiteral(String(val))});`,
      ].join('\n'),
    )
    .join('\n');
}

function formatScreenshot(args: Record<string, unknown>): string {
  const filePath = args.path as string | undefined;
  const fullPage = (args.fullPage as boolean | undefined) ?? false;
  const opts: string[] = [`fullPage: ${fullPage}`];
  if (filePath) opts.push(`path: ${jsLiteral(filePath)}`);
  return `  await page.screenshot({ ${opts.join(', ')} });`;
}

function formatWaitFor(args: Record<string, unknown>): string {
  const type = args.type as string | undefined;
  const value = args.value as string | undefined;
  const timeout = (args.timeout as number | undefined) ?? 30000;
  switch (type) {
    case 'selector':
      return `  await page.waitForSelector(${jsLiteral(value)}, { timeout: ${timeout} });`;
    case 'selector_hidden':
      return `  await page.waitForSelector(${jsLiteral(value)}, { timeout: ${timeout}, hidden: true });`;
    case 'function':
      // value is JS source; embed as a function body via new Function-style anonymous arrow.
      return `  await page.waitForFunction(${jsLiteral(value ?? 'true')}, { timeout: ${timeout} });`;
    case 'navigation':
      return `  await page.waitForNavigation({ timeout: ${timeout}, waitUntil: "domcontentloaded" });`;
    case 'url_match':
      return `  await page.waitForFunction((p: string) => new RegExp(p).test(window.location.href), { timeout: ${timeout} }, ${jsLiteral(value)});`;
    case 'timeout':
      return `  await new Promise<void>((r) => setTimeout(r, ${Number(value) || 1000}));`;
    default:
      return `  // wait_for type="${type ?? 'unknown'}" — no Puppeteer mapping`;
  }
}

function formatJavascript(args: Record<string, unknown>): string {
  const code = args.code as string | undefined;
  return `  await page.evaluate(${jsLiteral(code ?? '')});`;
}

function formatTabsCreate(args: Record<string, unknown>): string {
  const url = args.url as string | undefined;
  return [
    `  {`,
    `    const newPage = await browser.newPage();`,
    `    await newPage.goto(${jsLiteral(url)}, { waitUntil: "domcontentloaded" });`,
    `    page = newPage;`,
    `  }`,
  ].join('\n');
}

function formatTabsClose(args: Record<string, unknown>): string {
  const tabIds = args.tabIds as string[] | undefined;
  const tabId = args.tabId as string | undefined;
  const ids = tabIds && tabIds.length > 0 ? tabIds : tabId ? [tabId] : [];
  if (ids.length === 0) {
    return '  // tabs_close: no tabIds supplied (worker-scoped close not representable as plain puppeteer)';
  }
  return [
    `  {`,
    `    const targetIds = new Set<string>(${JSON.stringify(ids)});`,
    `    const pages = await browser.pages();`,
    `    for (const p of pages) {`,
    `      const client = await p.target().createCDPSession();`,
    `      const info = await client.send('Target.getTargetInfo');`,
    `      await client.detach();`,
    `      if (targetIds.has(info.targetInfo.targetId)) await p.close();`,
    `    }`,
    `  }`,
  ].join('\n');
}
