/**
 * Puppeteer TypeScript snippet generator (issue #836).
 *
 * Emits one snippet line (or a small block) per tool call for the nine
 * tools enumerated in the issue: navigate, interact, form_input, fill_form,
 * page_screenshot, wait_for, javascript_tool, tabs_create, tabs_close.
 *
 * Snippets are intentionally minimal — the goal is "what happened",
 * not "production-grade test". They assume a single shared `page`
 * variable (provided by the file header from aggregator.ts) and consume
 * the same `args` object that arrives at the tool handler. Secrets
 * placeholders (`${SECRET:NAME}`) pass through unchanged when the
 * secrets-hook supplies pre-substitution args; otherwise the post-
 * substitution literal value is embedded (see issue #834 dependency).
 */

import { jsLiteral } from './shared';

/**
 * Tools that have a per-tool Puppeteer snippet. The aggregator gates on
 * this set: tools outside it emit only mcp-replay envelopes.
 */
export const PUPPETEER_SUPPORTED_TOOLS: ReadonlySet<string> = new Set([
  'navigate',
  'interact',
  'form_input',
  'fill_form',
  'page_screenshot',
  'wait_for',
  'javascript_tool',
  'tabs_create',
  'tabs_close',
]);

/** Header prepended to the puppeteer TS session file on first append. */
export const PUPPETEER_FILE_HEADER = [
  '// Generated by openchrome --codegen puppeteer',
  '// Replay this script with: npx tsx <thisfile>',
  "import puppeteer from 'puppeteer-core';",
  '',
  'async function main(): Promise<void> {',
  '  const browser = await puppeteer.connect({ browserURL: process.env.CHROME_URL ?? "http://localhost:9222" });',
  '  const pages = await browser.pages();',
  '  const page = pages[0] ?? (await browser.newPage());',
  '',
].join('\n');

/** Footer appended to the puppeteer TS session file at session end. */
export const PUPPETEER_FILE_FOOTER = [
  '',
  '  await browser.disconnect();',
  '}',
  '',
  'main().catch((err) => {',
  '  console.error(err);',
  '  process.exit(1);',
  '});',
  '',
].join('\n');

/**
 * Build a Puppeteer snippet for the given tool call.
 *
 * Returns a string of one or more indented TS statements (no trailing
 * newline; the aggregator adds it). Returns `null` when the tool is not
 * one of the nine supported tools — callers that hit `null` fall back
 * to mcp-replay capture.
 */
export function formatPuppeteer(
  tool: string,
  args: Record<string, unknown>,
): string | null {
  if (!PUPPETEER_SUPPORTED_TOOLS.has(tool)) return null;

  switch (tool) {
    case 'navigate':
      return formatNavigate(args);
    case 'interact':
      return formatInteract(args);
    case 'form_input':
      return formatFormInput(args);
    case 'fill_form':
      return formatFillForm(args);
    case 'page_screenshot':
      return formatScreenshot(args);
    case 'wait_for':
      return formatWaitFor(args);
    case 'javascript_tool':
      return formatJavascript(args);
    case 'tabs_create':
      return formatTabsCreate(args);
    case 'tabs_close':
      return formatTabsClose(args);
    default:
      // Unreachable given the gate above, but the compiler insists.
      return null;
  }
}

function formatNavigate(args: Record<string, unknown>): string {
  const url = args.url as string | undefined;
  if (url === 'back') return '  await page.goBack({ waitUntil: "domcontentloaded" });';
  if (url === 'forward') return '  await page.goForward({ waitUntil: "domcontentloaded" });';
  return `  await page.goto(${jsLiteral(url)}, { waitUntil: "domcontentloaded" });`;
}

function formatInteract(args: Record<string, unknown>): string {
  const action = (args.action as string | undefined) ?? 'click';
  const selector = args.selector as string | undefined;
  const text = args.text as string | undefined;

  if (action === 'click') {
    return `  await page.click(${jsLiteral(selector)});`;
  }
  if (action === 'type' || action === 'fill') {
    return [
      `  await page.click(${jsLiteral(selector)});`,
      `  await page.keyboard.type(${jsLiteral(text ?? '')});`,
    ].join('\n');
  }
  if (action === 'hover') {
    return `  await page.hover(${jsLiteral(selector)});`;
  }
  if (action === 'focus') {
    return `  await page.focus(${jsLiteral(selector)});`;
  }
  // Catch-all: emit a comment + a click attempt so the file still parses.
  return [
    `  // interact action="${action}" — replayed as click for fallback compatibility`,
    `  await page.click(${jsLiteral(selector)});`,
  ].join('\n');
}

function formatFormInput(args: Record<string, unknown>): string {
  const selector = args.selector as string | undefined;
  const value = args.value as string | undefined;
  // form_input semantics: type into the focused element after focusing the selector.
  // We use page.type which clears and types in one call for inputs/textareas.
  return [
    `  await page.click(${jsLiteral(selector)}, { clickCount: 3 });`,
    `  await page.type(${jsLiteral(selector)}, ${jsLiteral(value ?? '')});`,
  ].join('\n');
}

function formatFillForm(args: Record<string, unknown>): string {
  const fields = (args.fields ?? args.values) as
    | Array<{ selector?: string; value?: string }>
    | Record<string, string>
    | undefined;
  if (!fields) {
    return '  // fill_form: no fields supplied';
  }
  if (Array.isArray(fields)) {
    return fields
      .map((f) =>
        [
          `  await page.click(${jsLiteral(f.selector)}, { clickCount: 3 });`,
          `  await page.type(${jsLiteral(f.selector)}, ${jsLiteral(f.value ?? '')});`,
        ].join('\n'),
      )
      .join('\n');
  }
  // Map form { "#sel": "value", ... }
  return Object.entries(fields)
    .map(([sel, val]) =>
      [
        `  await page.click(${jsLiteral(sel)}, { clickCount: 3 });`,
        `  await page.type(${jsLiteral(sel)}, ${jsLiteral(String(val))});`,
      ].join('\n'),
    )
    .join('\n');
}

function formatScreenshot(args: Record<string, unknown>): string {
  const filePath = args.path as string | undefined;
  const fullPage = (args.fullPage as boolean | undefined) ?? false;
  const opts: string[] = [`fullPage: ${fullPage}`];
  if (filePath) opts.push(`path: ${jsLiteral(filePath)}`);
  return `  await page.screenshot({ ${opts.join(', ')} });`;
}

function formatWaitFor(args: Record<string, unknown>): string {
  const type = args.type as string | undefined;
  const value = args.value as string | undefined;
  const timeout = (args.timeout as number | undefined) ?? 30000;
  switch (type) {
    case 'selector':
      return `  await page.waitForSelector(${jsLiteral(value)}, { timeout: ${timeout} });`;
    case 'selector_hidden':
      return `  await page.waitForSelector(${jsLiteral(value)}, { timeout: ${timeout}, hidden: true });`;
    case 'function':
      // value is JS source; embed as a function body via new Function-style anonymous arrow.
      return `  await page.waitForFunction(${jsLiteral(value ?? 'true')}, { timeout: ${timeout} });`;
    case 'navigation':
      return `  await page.waitForNavigation({ timeout: ${timeout}, waitUntil: "domcontentloaded" });`;
    case 'url_match':
      return `  await page.waitForFunction((p: string) => new RegExp(p).test(window.location.href), { timeout: ${timeout} }, ${jsLiteral(value)});`;
    case 'timeout':
      return `  await new Promise<void>((r) => setTimeout(r, ${Number(value) || 1000}));`;
    default:
      return `  // wait_for type="${type ?? 'unknown'}" — no Puppeteer mapping`;
  }
}

function formatJavascript(args: Record<string, unknown>): string {
  const code = args.code as string | undefined;
  return `  await page.evaluate(${jsLiteral(code ?? '')});`;
}

function formatTabsCreate(args: Record<string, unknown>): string {
  const url = args.url as string | undefined;
  return [
    `  {`,
    `    const newPage = await browser.newPage();`,
    `    await newPage.goto(${jsLiteral(url)}, { waitUntil: "domcontentloaded" });`,
    `  }`,
  ].join('\n');
}

function formatTabsClose(args: Record<string, unknown>): string {
  const tabIds = args.tabIds as string[] | undefined;
  const tabId = args.tabId as string | undefined;
  const ids = tabIds && tabIds.length > 0 ? tabIds : tabId ? [tabId] : [];
  if (ids.length === 0) {
    return '  // tabs_close: no tabIds supplied (worker-scoped close not representable as plain puppeteer)';
  }
  return [
    `  {`,
    `    const targetIds: string[] = ${JSON.stringify(ids)};`,
    `    const pages = await browser.pages();`,
    `    for (const p of pages) {`,
    `      // Puppeteer does not expose CDP targetId on Page; close every page by URL match as a best-effort.`,
    `      if (targetIds.length > 0) { await p.close(); }`,
    `    }`,
    `  }`,
  ].join('\n');
}
